add detection of Vitis version to determine EDF version

diff --git a/build_edf b/build_edf
--- a/build_edf
+++ b/build_edf
@@ -8,9 +8,18 @@ ROOTDIR=$PWD
 
 #For generate machine conf
 SDT_LOCATION=vivado-hw/sdt
+LOPPER=$(which lopper)
 
+#Lopper is currently dependent on Vitis version (2026.1 EDF relies on newer lopper)
+if [[ $LOPPER == *"2025.2"* ]]; then
+    repo init -u https://github.com/Xilinx/yocto-manifests.git -b rel-v2025.2 -m default-edf.xml
+elif [[ $LOPPER == *"2026.1"* ]]; then
+    repo init -u https://github.com/Xilinx/yocto-manifests.git -b rel-v2026.1 -m default-edf.xml
+else
+    echo "Local lopper installation not supported, cannot figure out required EDF version"
+    exit 1
+fi
 
-repo init -u https://github.com/Xilinx/yocto-manifests.git -b rel-v2025.2 -m default-edf.xml
 
 #Patch for Cisco Umbrella
 patch -p1 --ignore-whitespace << 'EOF'
